# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06a7e4ad5237ef0a0baf6e5c4e915258df0b27baed82fc426128d310d521173edea902d480e8d4c456de57c204a7f65acbead3efc35703c2808aa95518a09e81

test:
  secret_key_base: 9c1c7acf51f3a8d4c613b7bc0e0a65e99a4e51fd74a7f9151a558db8bb3eb7d9f3b17c09ae8ca55e3d852c81f688aa3ddb621eae977f14530bda0ab96cc9bcf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
